force-app/main/default/objects/UPP_Order_Acknowledgement__c/UPP_Order_Acknowledgement__c.object-meta.xml
<CustomObject>
    <label>UPP Order Acknowledgement</label>
    <nameField>
        <label>UPP Order Acknowledgement Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>UPP Order Acknowledgements</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/UPP_Order_Acknowledgement__c/fields/Account__c.field-meta.xml
<CustomField>
    <fullName>Account__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Account</label>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>UPP Order Acknowledgements (Account)</relationshipLabel>
    <relationshipName>UPP_Order_Acknowledgements1</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/UPP_Order_Acknowledgement__c/fields/File_Name__c.field-meta.xml
<CustomField>
    <fullName>File_Name__c</fullName>
    <label>File Name</label>
    <type>Url</type>
</CustomField>

force-app/main/default/objects/UPP_Order_Acknowledgement__c/fields/Order__c.field-meta.xml
<CustomField>
    <fullName>Order__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Order</label>
    <referenceTo>Order</referenceTo>
    <relationshipLabel>UPP Order Acknowledgements</relationshipLabel>
    <relationshipName>UPP_Order_Acknowledgements</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/UPP_Order_Acknowledgement__c/fields/Sold_To_Customer_Id__c.field-meta.xml
<CustomField>
    <fullName>Sold_To_Customer_Id__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Sold To Customer Id</label>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>UPP Order Acknowledgements</relationshipLabel>
    <relationshipName>UPP_Order_Acknowledgements</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/UPP_Order_Acknowledgement__c/fields/User__c.field-meta.xml
<CustomField>
    <fullName>User__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>User</label>
    <referenceTo>User</referenceTo>
    <relationshipName>UPP_Order_Acknowledgements</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/classes/CZ_UppOrderAcknowledgementController.cls
public with sharing class CZ_UppOrderAcknowledgementController {
    
    @AuraEnabled
    public static List<Upp_Order_Acknowledgement__c> fetchUppOrderAcknowledgements(Id orderId){
        List<Upp_Order_Acknowledgement__c> uppOrderAckList;
        try {
            uppOrderAckList  =[Select Id, Account__r.Name ,Sold_To_Customer_Id__r.Id,Sold_To_Customer_Id__r.Name,	File_Name__c,	Order__r.OrderNumber , Document_Link__c,User__c from Upp_Order_Acknowledgement__c Where User__c=:UserInfo.getUserId() AND Order__c=:orderId];
            return uppOrderAckList;
        } catch (Exception e) {
            throw new AuraHandledException(e.getMessage());
        }
        
    }
}