force-app/main/default/objects/UPP_User_Permission__c/UPP_User_Permission__c.object-meta.xml
<CustomObject>
    <label>UPP User Permission</label>
    <nameField>
        <displayFormat>PERM--{000000000}</displayFormat>
        <label>UPP User Permission Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>UPP User Permissions</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/UPP_User_Permission__c/fields/Contact__c.field-meta.xml
<CustomField>
    <fullName>Contact__c</fullName>
    <deleteConstraint>Restrict</deleteConstraint>
    <label>Contact</label>
    <referenceTo>Contact</referenceTo>
    <relationshipLabel>UPP User Permissions</relationshipLabel>
    <relationshipName>UPP_User_Permissions</relationshipName>
    <required>true</required>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/UPP_User_Permission__c/fields/Permission_Set_Api_Name__c.field-meta.xml
<CustomField>
    <fullName>Permission_Set_Api_Name__c</fullName>
    <label>UPP Program Permission Name</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/classes/UPPUserPermissionSelector.cls
public without sharing class UPPUserPermissionSelector extends fflib_SObjectSelector {
    
    // Specify the SObject Type
    public  Schema.SObjectType getSObjectType() {
        return UPP_User_Permission__c.SObjectType;
    }
    
    // Specify the Fields to Query
    public  List<Schema.SObjectField> getSObjectFieldList() {
        return new List<Schema.SObjectField>{
            UPP_User_Permission__c.Id,
            UPP_User_Permission__c.Permission_Set_Api_Name__c,
            UPP_User_Permission__c.Contact__c,
            UPP_User_Permission__c.Contact__r.Id
        };
    }
    
    // Method to Query Permissions by ContactId
    public List<UPP_User_Permission__c> selectPermissionsByContactId(Id contactId) {
        fflib_QueryFactory queryFactory = newQueryFactory();
        queryFactory.setCondition('Contact__r.Id = :contactId');
        
        return (List<UPP_User_Permission__c>) Database.query(queryFactory.toSOQL());
    }
}