force-app/main/default/objects/UPP_Notification__c/UPP_Notification__c.object-meta.xml
<CustomObject>
   
  
    <label>UPP Notification</label>
    <nameField>
        <displayFormat>Note-{00000000}</displayFormat>
        <label>UPP Notification Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>UPP Notifications</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/UPP_Notification__c/fields/Merge_Data__c.field-meta.xml
<CustomField>
    <fullName>Merge_Data__c</fullName>
    <label>Merge Data</label>
    <length>32768</length>
    <type>LongTextArea</type>
</CustomField>

force-app/main/default/objects/UPP_Notification__c/fields/Message__c.field-meta.xml
<CustomField>
    <fullName>Message__c</fullName>
    <label>Message</label>
    <length>32768</length>
    <type>Html</type>
</CustomField>

force-app/main/default/objects/UPP_Notification__c/fields/Theme__c.field-meta.xml
<CustomField>
    <fullName>Theme__c</fullName>
    <label>Theme</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Success</fullName>
            </value>
            <value>
                <fullName>Warning</fullName>
            </value>
            <value>
                <fullName>Error</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/UPP_Notification__c/fields/UPP_NotificationTemplate__c.field-meta.xml
<CustomField>
    <fullName>UPP_NotificationTemplate__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>UPP NotificationTemplate</label>
    <referenceTo>UPP_NotificationTemplate__c</referenceTo>
    <relationshipLabel>UPP Notifications</relationshipLabel>
    <relationshipName>UPP_Notifications</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/UPP_Notification__c/fields/User__c.field-meta.xml
<CustomField>
    <fullName>User__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>User</label>
    <referenceTo>User</referenceTo>
    <relationshipName>UPP_Notifications</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/UPP_Notifications_Preferences__c/UPP_Notifications_Preferences__c.object-meta.xml
<CustomObject>
    <label>UPP Notifications Preferences</label>
    <nameField>
        <label>UPP Notifications Preferences Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>UPP Notifications Preferences</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/UPP_Notifications_Preferences__c/fields/Deliver_message_by_email__c.field-meta.xml
<CustomField>
    <fullName>Deliver_message_by_email__c</fullName>
    <defaultValue>false</defaultValue>
    <label>Deliver message by email</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/UPP_Notifications_Preferences__c/fields/Preferences__c.field-meta.xml
<CustomField>
    <fullName>Preferences__c</fullName>
    <label>Preferences</label>
    <type>MultiselectPicklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Missed Pickup Appointment</fullName>
            </value>
            <value>
                <fullName>New Price Announcement</fullName>
            </value>
            <value>
                <fullName>Past Due Shipment</fullName>
            </value>
            <value>
                <fullName>Scheduled Ship Date Change</fullName>
            </value>
            <value>
                <fullName>Sales Incentive Credit Message</fullName>
            </value>
            <value>
                <fullName>New Statement</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/UPP_Notifications_Preferences__c/fields/Records_per_page__c.field-meta.xml
<CustomField>
    <fullName>Records_per_page__c</fullName>
    <defaultValue>10</defaultValue>
    <label>Records per page</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/UPP_Notifications_Preferences__c/fields/User__c.field-meta.xml
<CustomField>
    <fullName>User__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>User</label>
    <referenceTo>User</referenceTo>
    <relationshipName>UPP_Notifications_Preferences</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/UPP_NotificationTemplate__c/UPP_NotificationTemplate__c.object-meta.xml
<CustomObject>
    <label>UPP Notification Template</label>
    <nameField>
        <label>UPP_NotificationTemplate Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>UPP Notification Templates</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/UPP_NotificationTemplate__c/fields/Agreement_Text__c.field-meta.xml
<CustomField>
    <fullName>Agreement_Text__c</fullName>
    <label>Notification Text</label>
    <length>131072</length>
    <type>Html</type>
</CustomField>

force-app/main/default/classes/UPP_Notification_Helper_Test.cls
@IsTest
public class UPP_Notification_Helper_Test {

    @TestSetup
    static void setupData() {
       
         User ownerWithRole = [SELECT Id FROM User WHERE Profile.Name = 'System Administrator' AND UserRoleId != null LIMIT 1];
        Account acc = new Account(Name = 'Test Portal Account', OwnerId = ownerWithRole.Id);
        insert acc;
        Contact con = new Contact(FirstName = 'John', LastName = 'Doe', Email = 'johndoe@example.com',AccountId=acc.Id);
        insert con;
        Profile portalProfile = [SELECT Id FROM Profile WHERE Name = 'Customer Community Login User']; // Use relevant profile
         
        // Create test User 
        User portalUser = new User(
            FirstName = 'John',
        LastName = 'Doe',
        Email = 'johndoe@example.com',
        Username = 'johndoe@example.com.community',
        Alias = 'jdoe',
        TimeZoneSidKey = 'America/New_York',
        LocaleSidKey = 'en_US',
        EmailEncodingKey = 'UTF-8',
        ProfileId = portalProfile.Id,
        LanguageLocaleKey = 'en_US',
        ContactId = con.Id
            );
        insert portalUser;

        // Create Notification Preferences
        UPP_Notifications_Preferences__c pref = new UPP_Notifications_Preferences__c(
        User__c = portalUser.Id,
        Preferences__c = 'Missed Pickup Appointment',
        Deliver_Message_By_Email__c = true,
        Records_Per_Page__c = 5,
        Name = 'Test Preferences',
        OwnerId = portalUser.Id
        );
        insert pref;

        // Create Notification Template
        UPP_NotificationTemplate__c template = new UPP_NotificationTemplate__c(
            Agreement_Text__c = 'PO Number: [PONUMBER}, Order Number: [ORDERID] , ExtraTest: [EXTRATEST]'
        );
        insert template;
    }

    @isTest
    static void testAfterUppNotificationInsert_Success() {

            // Create Notification with Merge Data
        UPP_Notification__c notification = new UPP_Notification__c(
            User__c = [SELECT Id FROM User where Username = 'johndoe@example.com.community' LIMIT 1].Id,
            UPP_NotificationTemplate__c = [SELECT Id FROM UPP_NotificationTemplate__c LIMIT 1].Id,
            Merge_Data__c = '{"PONumber": "12345", "OrderNumber": "67890","ExtraTest": "ExtraVal"}',
            Theme__c = 'Success'
        );
        insert notification;

        // Verify Notification Message Merge
        UPP_Notification__c updatedNotification = [SELECT Message__c FROM UPP_Notification__c WHERE Id = :notification.Id];
      
        System.assertEquals('PO Number: 12345, Order Number: 67890 , ExtraTest: ExtraVal', updatedNotification.Message__c);
        
        
    }
    
    
      @isTest
    static void testAfterUppNotificationInsert_WithoutUser() {
   
            // Create Notification with Merge Data
        UPP_Notification__c notification = new UPP_Notification__c(
            UPP_NotificationTemplate__c = [SELECT Id FROM UPP_NotificationTemplate__c LIMIT 1].Id,
            Merge_Data__c = '{"PONumber": "12345", "OrderNumber": "67890", "ExtraTest": "ExtraVal"}',
            Theme__c = 'Success'
        );
        insert notification;
            
        // Verify Notification Message Merge
        UPP_Notification__c updatedNotification = [SELECT Message__c FROM UPP_Notification__c WHERE Id = :notification.Id];
          
        System.assertEquals('PO Number: 12345, Order Number: 67890 , ExtraTest: ExtraVal', updatedNotification.Message__c);
        
        
    }
    
     @isTest
    public static void testMergeFields_ExceptionHandling() {

        // Set up invalid JSON data to trigger an exception
        String invalidJson = '{ "PONumber": "12345", "OrderNumber": "67890" '; // Missing closing brace
        UPP_Notification__c notification = new UPP_Notification__c(
            User__c = [SELECT Id FROM User where Username = 'johndoe@example.com.community' LIMIT 1].Id,
            UPP_NotificationTemplate__c = [SELECT Id FROM UPP_NotificationTemplate__c LIMIT 1].Id,
            Merge_Data__c = invalidJson,
            Theme__c = 'Success'
        );
  

        
        // Execute the mergeFields method with invalid JSON to trigger an exception
        Test.startTest();
        try {
               insert notification;
        } catch (Exception e) {
            // Ensure the exception is caught
            System.debug('Caught exception: ' + e.getMessage());
        }
        Test.stopTest();
    }
}