force-app/main/default/objects/UPP_Notification__c/UPP_Notification__c.object-meta.xml
<CustomObject>
   
  
    <label>UPP Notification</label>
    <nameField>
        <displayFormat>Note-{00000000}</displayFormat>
        <label>UPP Notification Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>UPP Notifications</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/UPP_Notification__c/fields/Account__c.field-meta.xml
<CustomField>
    <fullName>Account__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Account</label>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>UPP Notifications</relationshipLabel>
    <relationshipName>UPP_Notifications</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/UPP_Notification__c/fields/Active__c.field-meta.xml
<CustomField>
    <fullName>Active__c</fullName>
    <defaultValue>true</defaultValue>
    <label>Is Active</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/UPP_Notification__c/fields/Business_Area__c.field-meta.xml
<CustomField>
    <fullName>Business_Area__c</fullName>
    <label>Business Area</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Mixed</fullName>
            </value>
            <value>
                <fullName>Commercial</fullName>
            </value>
            <value>
                <fullName>Residential</fullName>
            </value>
            <value>
                <fullName>ALL</fullName>
                <isActive>false</isActive>
                <label>ALL</label>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/UPP_Notification__c/fields/Certification_Visibility__c.field-meta.xml
<CustomField>
    <fullName>Certification_Visibility__c</fullName>
    <label>Certification Visibility</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Mixed</fullName>
            </value>
            <value>
                <fullName>Certified</fullName>
            </value>
            <value>
                <fullName>Non-Certified</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/UPP_Notification__c/fields/Dismissable__c.field-meta.xml
<CustomField>
    <fullName>Dismissable__c</fullName>
    <defaultValue>false</defaultValue>
    <label>Dismissable</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/UPP_Notification__c/fields/Evaluate_As__c.field-meta.xml
<CustomField>
    <fullName>Evaluate_As__c</fullName>
    <inlineHelpText>How the Permission Set entries are evaluated, does the context User need to be assigned to ALL listed entries or to ANY entry.</inlineHelpText>
    <label>Evaluate As</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>All Permission Sets</fullName>
            </value>
            <value>
                <fullName>Any Permission Set</fullName>
            </value>
            <value>
                <fullName>ALL</fullName>
                <isActive>false</isActive>
                <label>ALL</label>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/UPP_Notification__c/fields/Force_Refresh__c.field-meta.xml
<CustomField>
    <fullName>Force_Refresh__c</fullName>
    <defaultValue>false</defaultValue>
    <inlineHelpText>Checking this box will refresh the ENTIRE Notification with merge data from the associated template.</inlineHelpText>
    <label>Force Refresh</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/UPP_Notification__c/fields/Is_Visible__c.field-meta.xml
<CustomField>
    <fullName>Is_Visible__c</fullName>
    <formula>AND(Active__c, OR(ISBLANK(Start_Date__c), Start_Date__c &lt;= TODAY()), OR(ISBLANK(End_Date__c), End_Date__c &gt;= TODAY()))</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Is Visible</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/UPP_Notification__c/fields/Merge_Data__c.field-meta.xml
<CustomField>
    <fullName>Merge_Data__c</fullName>
    <label>Merge Data</label>
    <length>32768</length>
    <type>LongTextArea</type>
</CustomField>

force-app/main/default/objects/UPP_Notification__c/fields/Message__c.field-meta.xml
<CustomField>
    <fullName>Message__c</fullName>
    <label>Message</label>
    <length>32768</length>
    <type>Html</type>
</CustomField>

force-app/main/default/objects/UPP_Notification__c/fields/Message_Type__c.field-meta.xml
<CustomField>
    <fullName>Message_Type__c</fullName>
    <label>Message Type</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>Missed Pickup Appointment</fullName>
            </value>
            <value>
                <fullName>Past Due Shipment</fullName>
            </value>
            <value>
                <fullName>Scheduled Ship Date Change</fullName>
            </value>
            <value>
                <fullName>Sales Incentive Credit Message</fullName>
            </value>
            <value>
                <fullName>New Statement</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/UPP_Notification__c/fields/Page_Visibility__c.field-meta.xml
<CustomField>
    <fullName>Page_Visibility__c</fullName>
    <label>Page Visibility</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Home</fullName>
            </value>
            <value>
                <fullName>All</fullName>
            </value>
            <value>
                <fullName>My Company Profile</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/UPP_Notification__c/fields/Permission_Sets__c.field-meta.xml
<CustomField>
    <fullName>Permission_Sets__c</fullName>
    <label>Permission Set(s)</label>
    <type>MultiselectPicklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>UPP_Add_manage_and_remove_users_permissions_and_services</fullName>
            </value>
            <value>
                <fullName>UPP_Manage_users_permissions_and_program_enrollment</fullName>
            </value>
            <value>
                <fullName>UPP_CMS_Home_Access</fullName>
            </value>
            <value>
                <fullName>UPP_Edit_Company_Info_and_Profile</fullName>
            </value>
            <value>
                <fullName>UPP_Manage_External_Users</fullName>
            </value>
            <value>
                <fullName>UPP_View_Rewards_Widget</fullName>
            </value>
            <value>
                <fullName>UPP_View_Warranty_Guarantee_Widget</fullName>
            </value>
            <value>
                <fullName>UPP_Admin_User</fullName>
                <isActive>false</isActive>
                <label>UPP_Admin_User</label>
            </value>
            <value>
                <fullName>UPP_Integration</fullName>
                <isActive>false</isActive>
                <label>UPP_Integration</label>
            </value>
            <value>
                <fullName>UPP_Power_User</fullName>
                <isActive>false</isActive>
                <label>UPP_Power_User</label>
            </value>
            <value>
                <fullName>UPP_Standard_User</fullName>
                <isActive>false</isActive>
                <label>UPP_Standard_User</label>
            </value>
            <value>
                <fullName>UPP_Territory_Manager</fullName>
                <isActive>false</isActive>
                <label>UPP_Territory_Manager</label>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/UPP_Notification__c/fields/Process_Id__c.field-meta.xml
<CustomField>
    <fullName>Process_Id__c</fullName>
    <label>Process Id</label>
    <length>18</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/UPP_Notification__c/fields/Related_Id__c.field-meta.xml
<CustomField>
    <fullName>Related_Id__c</fullName>
    <label>Related Id</label>
    <length>18</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/UPP_Notification__c/fields/Related_Link__c.field-meta.xml
<CustomField>
    <fullName>Related_Link__c</fullName>
    <label>Related Link</label>
    <type>Url</type>
</CustomField>

force-app/main/default/objects/UPP_Notification__c/fields/Sent__c.field-meta.xml
<CustomField>
    <fullName>Sent__c</fullName>
    <label>Sent</label>
    <type>DateTime</type>
</CustomField>

force-app/main/default/objects/UPP_Notification__c/fields/Start_Enrollment__c.field-meta.xml
<CustomField>
    <fullName>Start_Enrollment__c</fullName>
    <defaultValue>true</defaultValue>
    <label>Start Enrollment</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/UPP_Notification__c/fields/Start_Message__c.field-meta.xml
<CustomField>
    <fullName>Start_Message__c</fullName>
    <label>Start Message</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/UPP_Notification__c/fields/Theme__c.field-meta.xml
<CustomField>
    <fullName>Theme__c</fullName>
    <label>Theme</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Success</fullName>
            </value>
            <value>
                <fullName>Warning</fullName>
            </value>
            <value>
                <fullName>Error</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/UPP_Notification__c/fields/Type__c.field-meta.xml
<CustomField>
    <fullName>Type__c</fullName>
    <label>Type</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Insurance Provided</fullName>
            </value>
            <value>
                <fullName>License Renewal</fullName>
            </value>
            <value>
                <fullName>T&amp;C Signed</fullName>
            </value>
            <value>
                <fullName>License Provided</fullName>
            </value>
            <value>
                <fullName>Certification Approved</fullName>
            </value>
            <value>
                <fullName>Installation Experience Provided</fullName>
            </value>
            <value>
                <fullName>Account Master Data Lock</fullName>
            </value>
            <value>
                <fullName>Insurance Renewal</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/UPP_Notification__c/fields/UPP_NotificationTemplate__c.field-meta.xml
<CustomField>
    <fullName>UPP_NotificationTemplate__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>UPP NotificationTemplate</label>
    <referenceTo>UPP_NotificationTemplate__c</referenceTo>
    <relationshipLabel>UPP Notifications</relationshipLabel>
    <relationshipName>UPP_Notifications</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/UPP_Notification__c/fields/User__c.field-meta.xml
<CustomField>
    <fullName>User__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>User</label>
    <referenceTo>User</referenceTo>
    <relationshipName>UPP_Notifications</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/UPP_Notification__c/recordTypes/Active.recordType-meta.xml
<RecordType>
    <fullName>Active</fullName>
    <active>true</active>
    <label>Active</label>
</RecordType>

force-app/main/default/objects/UPP_NotificationTemplate__c/UPP_NotificationTemplate__c.object-meta.xml
<CustomObject>
    <label>UPP Notification Template</label>
    <nameField>
        <label>UPP_NotificationTemplate Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>UPP Notification Templates</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/UPP_NotificationTemplate__c/fields/Agreement_Sub_Type__c.field-meta.xml
<CustomField>
    <fullName>Agreement_Sub_Type__c</fullName>
    <label>Notification Sub-Type</label>
    <type>Picklist</type>
    <valueSet>
        <controllingField>Agreement_Type__c</controllingField>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Residential</fullName>
            </value>
            <value>
                <fullName>Commercial</fullName>
            </value>
            <value>
                <fullName>Rewards</fullName>
            </value>
            <value>
                <fullName>Leads</fullName>
            </value>
            <value>
                <fullName>Project</fullName>
            </value>
            <value>
                <fullName>Workbelt</fullName>
            </value>
            <value>
                <fullName>Company Wide</fullName>
            </value>
            <value>
                <fullName>Personal</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/UPP_NotificationTemplate__c/fields/Agreement_Text__c.field-meta.xml
<CustomField>
    <fullName>Agreement_Text__c</fullName>
    <label>Notification Text</label>
    <length>131072</length>
    <type>Html</type>
</CustomField>

force-app/main/default/objects/UPP_NotificationTemplate__c/fields/Notification_Type__c.field-meta.xml
<CustomField>
    <fullName>Notification_Type__c</fullName>
    <label>Notification Type</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Agreement</fullName>
            </value>
            <value>
                <fullName>TBD</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/classes/CZ_UPPNotificationSelector.cls
/**
 * @description       : 
 * @author            : rob.rastovich@gaf.com
 * @group             : 
 * @last modified on  : 04-02-2025
 * @last modified by  : rob.rastovich@gaf.com
**/
public inherited sharing class CZ_UPPNotificationSelector extends fflib_SObjectSelector {
    // Constructor for fflib
    
    
    public  List<Schema.SObjectField> getSObjectFieldList() {
        return new List<Schema.SObjectField>{
            UPP_Notification__c.Id,
            UPP_Notification__c.Business_Area__c,
            UPP_Notification__c.Is_Read__c,
            UPP_Notification__c.Message_Type__c,
            UPP_Notification__c.Subject__c,
            UPP_Notification__c.Sent__c,
            UPP_Notification__c.Message__c,
            UPP_Notification__c.User__c,
            UPP_Notification__c.User__r.Name,
            UPP_Notification__c.Related_Id__c,
            UPP_Notification__c.RecordTypeId,
            UPP_Notification__c.RecordType.Name,
            UPP_Notification__c.Related_Link__c,
            UPP_Notification__c.UPP_NotificationTemplate__c,
            UPP_Notification__c.Merge_Data__c
        };
    }
    public  Schema.SObjectType getSObjectType() {
        return UPP_Notification__c.SObjectType;
    }
    
    
    
    // Get Notifications using Filters
    public List<UPP_Notification__c> selectNotifications(
        Id currentUserId,
    Boolean showArchived,
    String messageStatus,
    String messageType,
    Date dateFrom,
    
    Date dateTo
    ) {
        fflib_QueryFactory queryFactory = newQueryFactory();
        
        
        system.debug('showArchived'+showArchived);
        //String conditionString  =
        String recType = 'Active';
        
        String conditionString = 'User__c = :currentUserId';
        if(showArchived==false){
            // queryFactory.selectField('RecordType.Name').setCondition('RecordType.Name = Active');
            conditionString+=' AND RecordType.Name = :recType';
            system.debug('queryFactory'+queryFactory);
        }
        
        
        if (messageStatus != 'None') {
            Boolean isRead = (messageStatus == 'Unread Only') ? false : true;
            conditionString+=' AND Is_Read__c = :isRead';
        }
        if (dateFrom != null) {
            conditionString+=' AND Sent__c >= :dateFrom';
        }
        if (dateTo != null) {
            conditionString+=' AND Sent__c <= :dateTo';
        }
        if (messageType != 'None') {
            conditionString+=' AND Message_Type__c = :messageType';
        }
        queryFactory.setCondition(conditionString);
        system.debug('query---'+queryFactory);
             system.debug('query - '+queryFactory.toSOQL());
        return (List<UPP_Notification__c>) Database.query(queryFactory.toSOQL());
    }
    public List<UPP_Notification__c> selectNotificationsById(List<Id> Ids){
        fflib_QueryFactory queryFactory = newQueryFactory();
        queryFactory.selectFields(getSObjectFieldList());
        queryFactory.selectField('UPP_NotificationTemplate__r.Agreement_Text__c');
        queryFactory.setCondition('Id IN :Ids');
        return (List<UPP_Notification__c>) Database.query(queryFactory.toSOQL());
    }
    public List<UPP_Notification__c> selectByTemplateAccount(String idAct,Set<id> idTemplate,String ord){
        fflib_QueryFactory query = newQueryFactory();
        query.selectFields(
                    new Set<String>{
                        'Account__c',
                        'Business_Area__c',
                        'Certification_Designation__c',
                        'Certification_Visibility__c',
                        'CreatedById',
                        'Dismissable__c',
                        'End_Date__c',
                        'Evaluate_As__c',
                        'Force_Refresh__c',
                        'Active__c',
                        'Is_Visible__c',
                        'LastModifiedById',
                        'Link__c',
                        'Message__c',
                        'OwnerId',
                        'Page_Visibility__c',
                        'Permission_Sets__c',
                        'Process_Id__c',
                        'RecordTypeId',
                        'Related_Id__c',
                        'Start_Date__c',
                        'Start_Enrollment__c',
                        'Start_Message__c',
                        'Template_Name__c',
                        'Theme__c',
                        'Type__c',
                        'Name',
                        'UPP_NotificationTemplate__c',
                        'UPP_NotificationTemplate__r.Notification_Type__c',
                        'UPP_NotificationTemplate__r.Agreement_Sub_Type__c'
                    }
                );
        query.setCondition('Active__c=true AND UPP_NotificationTemplate__c IN:idTemplate AND Account__c=:idAct ');
        query.setOrdering('UPP_NotificationTemplate__r.Agreement_Sub_Type__c', ord=='ASC'?fflib_QueryFactory.SortOrder.ASCENDING:fflib_QueryFactory.SortOrder.DESCENDING);
        return (List<UPP_Notification__c>)Database.query(query.toSOQL());
    }
    public UPP_Notification__c selectById(String idnt){
        fflib_QueryFactory query = newQueryFactory();
        query.setCondition('Id=:idnt');
    
        return (UPP_Notification__c)Database.query(query.toSOQL());
    }
}