force-app/main/default/objects/UPP_Notification__c/UPP_Notification__c.object-meta.xml
<CustomObject>
   
  
    <label>UPP Notification</label>
    <nameField>
        <displayFormat>Note-{00000000}</displayFormat>
        <label>UPP Notification Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>UPP Notifications</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/UPP_Notification__c/fields/Account__c.field-meta.xml
<CustomField>
    <fullName>Account__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Account</label>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>UPP Notifications</relationshipLabel>
    <relationshipName>UPP_Notifications</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/UPP_Notification__c/fields/Business_Area__c.field-meta.xml
<CustomField>
    <fullName>Business_Area__c</fullName>
    <label>Business Area</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Mixed</fullName>
            </value>
            <value>
                <fullName>Commercial</fullName>
            </value>
            <value>
                <fullName>Residential</fullName>
            </value>
            <value>
                <fullName>ALL</fullName>
                <isActive>false</isActive>
                <label>ALL</label>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/UPP_Notification__c/fields/Message_Type__c.field-meta.xml
<CustomField>
    <fullName>Message_Type__c</fullName>
    <label>Message Type</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>Missed Pickup Appointment</fullName>
            </value>
            <value>
                <fullName>Past Due Shipment</fullName>
            </value>
            <value>
                <fullName>Scheduled Ship Date Change</fullName>
            </value>
            <value>
                <fullName>Sales Incentive Credit Message</fullName>
            </value>
            <value>
                <fullName>New Statement</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/UPP_Notification__c/fields/Sent__c.field-meta.xml
<CustomField>
    <fullName>Sent__c</fullName>
    <label>Sent</label>
    <type>DateTime</type>
</CustomField>

force-app/main/default/objects/UPP_Notification__c/fields/Theme__c.field-meta.xml
<CustomField>
    <fullName>Theme__c</fullName>
    <label>Theme</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Success</fullName>
            </value>
            <value>
                <fullName>Warning</fullName>
            </value>
            <value>
                <fullName>Error</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/UPP_Notification__c/fields/User__c.field-meta.xml
<CustomField>
    <fullName>User__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>User</label>
    <referenceTo>User</referenceTo>
    <relationshipName>UPP_Notifications</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/UPP_Notification__c/recordTypes/Active.recordType-meta.xml
<RecordType>
    <fullName>Active</fullName>
    <active>true</active>
    <label>Active</label>
</RecordType>

force-app/main/default/objects/UPP_Notifications_Preferences__c/UPP_Notifications_Preferences__c.object-meta.xml
<CustomObject>
    <label>UPP Notifications Preferences</label>
    <nameField>
        <label>UPP Notifications Preferences Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>UPP Notifications Preferences</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/UPP_Notifications_Preferences__c/fields/Deliver_message_by_email__c.field-meta.xml
<CustomField>
    <fullName>Deliver_message_by_email__c</fullName>
    <defaultValue>false</defaultValue>
    <label>Deliver message by email</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/UPP_Notifications_Preferences__c/fields/Preferences__c.field-meta.xml
<CustomField>
    <fullName>Preferences__c</fullName>
    <label>Preferences</label>
    <type>MultiselectPicklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Missed Pickup Appointment</fullName>
            </value>
            <value>
                <fullName>New Price Announcement</fullName>
            </value>
            <value>
                <fullName>Past Due Shipment</fullName>
            </value>
            <value>
                <fullName>Scheduled Ship Date Change</fullName>
            </value>
            <value>
                <fullName>Sales Incentive Credit Message</fullName>
            </value>
            <value>
                <fullName>New Statement</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/UPP_Notifications_Preferences__c/fields/Records_per_page__c.field-meta.xml
<CustomField>
    <fullName>Records_per_page__c</fullName>
    <defaultValue>10</defaultValue>
    <label>Records per page</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/UPP_Notifications_Preferences__c/fields/User__c.field-meta.xml
<CustomField>
    <fullName>User__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>User</label>
    <referenceTo>User</referenceTo>
    <relationshipName>UPP_Notifications_Preferences</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/UPP_User_Permission__c/UPP_User_Permission__c.object-meta.xml
<CustomObject>
    <label>UPP User Permission</label>
    <nameField>
        <displayFormat>PERM--{000000000}</displayFormat>
        <label>UPP User Permission Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>UPP User Permissions</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/UPP_User_Permission__c/fields/Account__c.field-meta.xml
<CustomField>
    <fullName>Account__c</fullName>
    <deleteConstraint>Restrict</deleteConstraint>
    <label>Location</label>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>UPP User Permissions</relationshipLabel>
    <relationshipName>UPP_User_Permissions</relationshipName>
    <required>true</required>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/UPP_User_Permission__c/fields/Business_Area__c.field-meta.xml
<CustomField>
    <fullName>Business_Area__c</fullName>
    <label>Business Area</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Residential</fullName>
            </value>
            <value>
                <fullName>Commercial</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/UPP_User_Permission__c/fields/Contact__c.field-meta.xml
<CustomField>
    <fullName>Contact__c</fullName>
    <deleteConstraint>Restrict</deleteConstraint>
    <label>Contact</label>
    <referenceTo>Contact</referenceTo>
    <relationshipLabel>UPP User Permissions</relationshipLabel>
    <relationshipName>UPP_User_Permissions</relationshipName>
    <required>true</required>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/UPP_User_Permission__c/fields/Permission_Set_Api_Name__c.field-meta.xml
<CustomField>
    <fullName>Permission_Set_Api_Name__c</fullName>
    <label>UPP Program Permission Name</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/UPP_User_Permission__c/fields/UPP_Permission_Key__c.field-meta.xml
<CustomField>
    <fullName>UPP_Permission_Key__c</fullName>
    <caseSensitive>true</caseSensitive>
    <description>Concatenation (Account__r.Id + Contact__r.Id + UPP_Program_Permission__r.Id)</description>
    <externalId>true</externalId>
    <inlineHelpText>Concatenation (Account__r.Id + Contact__r.Id + UPP_Program_Permission__r.Id)</inlineHelpText>
    <label>UPP Permission Key</label>
    <length>54</length>
    <required>true</required>
    <type>Text</type>
    <unique>true</unique>
</CustomField>

force-app/main/default/objects/UPP_User_Permission__c/fields/UPP_Program_Permission_Id__c.field-meta.xml
<CustomField>
    <fullName>UPP_Program_Permission_Id__c</fullName>
    <label>UPP Program Permission Id</label>
    <length>18</length>
    <required>true</required>
    <type>Text</type>
</CustomField>

force-app/main/default/classes/UPPNotificationController_Test.cls
@isTest
public class UPPNotificationController_Test {
    
    @TestSetup
    static void setupTestData() {
        User ownerWithRole = [SELECT Id FROM User WHERE Profile.Name = 'System Administrator' AND UserRoleId != null LIMIT 1];
        Account acc = new Account(Name = 'Test Portal Account', OwnerId = ownerWithRole.Id);
        insert acc;
        Contact con = new Contact(FirstName = 'John', LastName = 'Doe', Email = 'johndoe@example.com',AccountId=acc.Id);
        insert con;
        Profile portalProfile = [SELECT Id FROM Profile WHERE Name = 'Customer Community Login User']; // Use relevant profile
        
        User portalUser = new User(
            FirstName = 'John',
        LastName = 'Doe',
        Email = 'johndoe@example.com',
        Username = 'johndoe@example.com.community',
        Alias = 'jdoe',
        TimeZoneSidKey = 'America/New_York',
        LocaleSidKey = 'en_US',
        EmailEncodingKey = 'UTF-8',
        ProfileId = portalProfile.Id,
        LanguageLocaleKey = 'en_US',
        ContactId = con.Id
            );
        insert portalUser;
        
        // Create UPP Notifications
        List<UPP_Notification__c> notifications = new List<UPP_Notification__c>();
        for (Integer i = 0; i < 5; i++) {
            notifications.add(new UPP_Notification__c(Business_Area__c = 'Mixed',Is_Read__c = true,Message_Type__c = 'Missed Pickup Appointment',Subject__c = 'Subject ' + i,  Sent__c = Date.today().addDays(-i), User__c = portalUser.Id,Theme__c='Success',RecordTypeId = [Select Id from RecordType where Name = 'Active' Limit 1].Id));
        }
        insert notifications;
        
        // Create UPP_Notifications_Preferences__c
        UPP_Notifications_Preferences__c preference = new UPP_Notifications_Preferences__c(
            User__c = portalUser.Id,
        Preferences__c = 'Missed Pickup Appointment;Past Due Shipment;',
        Deliver_Message_By_Email__c = true,
        Records_Per_Page__c = 5,
        Name = 'Test Preferences',
        OwnerId = portalUser.Id
            );
        insert preference;
        
        // Create UPP_User_Permission__c
        insert new List<UPP_User_Permission__c>{
            new UPP_User_Permission__c(
                Contact__c = portalUser.ContactId,
            Permission_Set_Api_Name__c = 'CZ_Missed_Pickup_Appointment',
            Account__c = acc.Id,
            UPP_Permission_Key__c='110000001',
            UPP_Program_Permission_Id__c ='1100000002'
                ),
            new UPP_User_Permission__c(
                Contact__c = portalUser.ContactId,
            Permission_Set_Api_Name__c = 'CZ_Past_Due_Shipment',
            Account__c = acc.Id,
            UPP_Permission_Key__c='110000002',
            UPP_Program_Permission_Id__c ='1100000003'
                )
        };
    }
    
    @isTest
    static void testGetUserNotifications() {
        Test.startTest();
        User runningTestPortalUser = [Select Id from User Where username='johndoe@example.com.community'];
        System.runAs(runningTestPortalUser){
            List<UPP_Notification__c> result = UPPNotificationController.getUserNotifications(
                Date.today().addDays(-1), Date.today().addDays(1), false, 'Read', 'Missed Pickup Appointment', 'Missed Pickup Appointment'
                );
            
            System.assertNotEquals(0, result.size());
        }
        
        
        Test.stopTest();
    }
    
    @isTest
    static void testGetUppNotificationPreferences() {
        Test.startTest();
        
        User runningTestPortalUser = [Select Id from User Where username='johndoe@example.com.community'];
        
        System.runAs(runningTestPortalUser){
            List<UPP_Notifications_Preferences__c> preferences = UPPNotificationController.getUppNotificationPreferences();
            System.assertEquals(1, preferences.size());
            System.assertEquals(true, preferences[0].Deliver_Message_By_Email__c);
            System.assertEquals(5, preferences[0].Records_Per_Page__c);
            System.assertEquals('Missed Pickup Appointment;Past Due Shipment', preferences[0].Preferences__c);
        }
        Test.stopTest();
    }
    
    @isTest
    static void testUpdatePreferences() {
        Test.startTest();
        User runningTestPortalUser = [Select Id from User Where username='johndoe@example.com.community'];
        system.debug('runningTestPortalUser'+runningTestPortalUser);
        
        
        
        
        System.runAs(runningTestPortalUser){
            Map<String, Object> preferences = new Map<String, Object>{
                'messageTypes' => 'Missed Pickup Appointment',
                'recordsPerPage' => 20
            };
            UPPNotificationController.saveOrUpdatePreferences(preferences);
            UPP_Notifications_Preferences__c updatedPref = [SELECT Preferences__c FROM UPP_Notifications_Preferences__c LIMIT 1];
            System.assertEquals('Missed Pickup Appointment', updatedPref.Preferences__c);
        }
        Test.stopTest();
    }
    @isTest
    static void testSavePreferences() {
        delete [Select Id from UPP_Notifications_Preferences__c];
        Map<String, Object> preferences = new Map<String, Object>{
            'messageTypes' => 'Missed Pickup Appointment',
            'recordsPerPage' => 20
        };
        UPPNotificationController.saveOrUpdatePreferences(preferences);
        UPP_Notifications_Preferences__c createdPref = [SELECT Preferences__c FROM UPP_Notifications_Preferences__c LIMIT 1];
        System.assertEquals('Missed Pickup Appointment', createdPref.Preferences__c);
    }
    
    @isTest
    static void testUpdateUppNotificationRecords() {
        
        List<UPP_Notification__c> notifications = [SELECT Id, RecordTypeId FROM UPP_Notification__c LIMIT 2];
        
        List<Map<String, String>> recordsToUpdate = new List<Map<String, String>>();
        for (UPP_Notification__c notif : notifications) {
            recordsToUpdate.add(new Map<String, String>{
                'Id' => notif.Id,
                'RecordTypeId' => notif.RecordTypeId
            });
        }
        
        Test.startTest();
        List<Map<String, String>> updatedRecords = UPPNotificationController.updateUppNotificationRecords(recordsToUpdate);
        System.assertEquals(2, updatedRecords.size());
        Test.stopTest();
    }
    
    //methods to check exceptions
    @isTest
    static void testUpdateUppNotificationRecords_Exception() {
        List<Map<String, String>> invalidRecords = new List<Map<String, String>>{
            new Map<String, String>{
                'Id' => 'InvalidId',
                'RecordTypeId' => 'InvalidRecordTypeId'
            }
        };
        
        Test.startTest();
        try {
            
            UPPNotificationController.updateUppNotificationRecords(invalidRecords);
            System.assert(false, 'Exception should have been thrown');
        } catch (AuraHandledException e) {
            
            System.debug('Exception Message: ' + e.getMessage());
            System.assert(e.getMessage().contains('Script-thrown exception'),
            'Expected exception message to contain "Script-thrown exception"');
        }
        Test.stopTest();
        
    }
    @isTest
    static void testSaveOrUpdatePreferences_TypeException() {
        
        Map<String, Object> invalidPreferences = new Map<String, Object>{
            'messageTypes' => 'Type1;Type2',
            'recordsPerPage' => 'InvalidValue' // This will cause a TypeException
        };
        
        Test.startTest();
        try {
            // Call the method to trigger the exception
            UPPNotificationController.saveOrUpdatePreferences(invalidPreferences);
            System.assert(false, 'Exception should have been thrown');
        } catch (AuraHandledException e) {
            
            // Validate the exception
            System.assert(e.getMessage().contains('Script-thrown exception'),
            'Expected exception message to indicate an invalid value');
        }
        Test.stopTest();
    }
    
    
    
}