force-app/main/default/objects/UPP_Notification__c/UPP_Notification__c.object-meta.xml
<CustomObject>
   
  
    <label>UPP Notification</label>
    <nameField>
        <displayFormat>Note-{00000000}</displayFormat>
        <label>UPP Notification Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>UPP Notifications</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/UPP_Notification__c/fields/Business_Area__c.field-meta.xml
<CustomField>
    <fullName>Business_Area__c</fullName>
    <label>Business Area</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Mixed</fullName>
            </value>
            <value>
                <fullName>Commercial</fullName>
            </value>
            <value>
                <fullName>Residential</fullName>
            </value>
            <value>
                <fullName>ALL</fullName>
                <isActive>false</isActive>
                <label>ALL</label>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/UPP_Notification__c/fields/Message__c.field-meta.xml
<CustomField>
    <fullName>Message__c</fullName>
    <label>Message</label>
    <length>32768</length>
    <type>Html</type>
</CustomField>

force-app/main/default/objects/UPP_Notification__c/fields/Message_Type__c.field-meta.xml
<CustomField>
    <fullName>Message_Type__c</fullName>
    <label>Message Type</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>Missed Pickup Appointment</fullName>
            </value>
            <value>
                <fullName>Past Due Shipment</fullName>
            </value>
            <value>
                <fullName>Scheduled Ship Date Change</fullName>
            </value>
            <value>
                <fullName>Sales Incentive Credit Message</fullName>
            </value>
            <value>
                <fullName>New Statement</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/UPP_Notification__c/fields/Sent__c.field-meta.xml
<CustomField>
    <fullName>Sent__c</fullName>
    <label>Sent</label>
    <type>DateTime</type>
</CustomField>

force-app/main/default/objects/UPP_Notification__c/fields/User__c.field-meta.xml
<CustomField>
    <fullName>User__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>User</label>
    <referenceTo>User</referenceTo>
    <relationshipName>UPP_Notifications</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/UPP_Notification__c/recordTypes/Active.recordType-meta.xml
<RecordType>
    <fullName>Active</fullName>
    <active>true</active>
    <label>Active</label>
</RecordType>

force-app/main/default/objects/UPP_Notifications_Preferences__c/UPP_Notifications_Preferences__c.object-meta.xml
<CustomObject>
    <label>UPP Notifications Preferences</label>
    <nameField>
        <label>UPP Notifications Preferences Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>UPP Notifications Preferences</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/UPP_Notifications_Preferences__c/fields/Preferences__c.field-meta.xml
<CustomField>
    <fullName>Preferences__c</fullName>
    <label>Preferences</label>
    <type>MultiselectPicklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Missed Pickup Appointment</fullName>
            </value>
            <value>
                <fullName>New Price Announcement</fullName>
            </value>
            <value>
                <fullName>Past Due Shipment</fullName>
            </value>
            <value>
                <fullName>Scheduled Ship Date Change</fullName>
            </value>
            <value>
                <fullName>Sales Incentive Credit Message</fullName>
            </value>
            <value>
                <fullName>New Statement</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/UPP_Notifications_Preferences__c/fields/User__c.field-meta.xml
<CustomField>
    <fullName>User__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>User</label>
    <referenceTo>User</referenceTo>
    <relationshipName>UPP_Notifications_Preferences</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/classes/UPPNotificationController.cls
public with sharing class UPPNotificationController {
    @AuraEnabled
    public static List<UPP_Notification__c> getUserNotifications(  
    Date dateFrom,
    Date dateTo,
    Boolean showArchived,
    String calledFrom,
    String messageStatus,
    String messageType,
    String preferencesString
    ) {

        Id currentUserId = UserInfo.getUserId();
       String recType ='Active';
       String baseQuery = showArchived? 'SELECT Id, Business_Area__c,Is_Read__c, Message_Type__c,Subject__c, Sent__c, Message__c, User__c ,User__r.Name FROM UPP_Notification__c WHERE User__c = :currentUserId' : 'SELECT Id, Business_Area__c,Is_Read__c, Message_Type__c,Subject__c, Sent__c, Message__c, User__c ,User__r.Name FROM UPP_Notification__c WHERE RecordType.Name = :recType And User__c = :currentUserId';
 
        List<String> conditions = new List<String>();
        system.debug('preferencesString'+preferencesString);
       if(preferencesString!=null){

         List<String> preferencesList = preferencesString.split(';');
         system.debug('preferencesList---'+preferencesList);
        conditions.add('Message_Type__c IN :preferencesList');
       }
        if(messageStatus!='None'){
            Boolean isRead = messageStatus=='Unread Only'?false:true;
            conditions.add('Is_Read__c = :isRead');
         }

            if (dateFrom != null) {
                conditions.add('Sent__c >= :dateFrom');
            }
            if (dateTo != null) {
                conditions.add('Sent__c <= :dateTo');
            }
            if(messageType!='None'){
                conditions.add('Message_Type__c = :messageType');
            }
        
        if (!conditions.isEmpty()) {
            baseQuery += ' AND ' + String.join(conditions, ' AND ');
        }
        return Database.query(baseQuery);
    }

  @AuraEnabled
   public static String getUppNotificationPreferences(){

        List<UPP_Notifications_Preferences__c>  preferencesList = [Select Id, Preferences__c from UPP_Notifications_Preferences__c where User__c=:UserInfo.getUserId()];
        return preferencesList[0].Preferences__c;
       }

       @AuraEnabled
      public static void saveOrUpdatePreferences(String preferences) {
        try {
            List<UPP_Notifications_Preferences__c>  preferencesList =[Select Id, Preferences__c from UPP_Notifications_Preferences__c where User__c=:UserInfo.getUserId()];
            if(preferencesList.isEmpty()){
                UPP_Notifications_Preferences__c preference = new UPP_Notifications_Preferences__c(Preferences__c = preferences,User__c= UserInfo.getUserId());
                insert preference;
            }
            else {
                preferencesList[0].Preferences__c = preferences;
                update preferencesList[0];
            }
        } catch (Exception e) {
            throw new AuraHandledException(e.getMessage());
        }
    }
}