force-app/main/default/objects/UPP_Notifications_Preferences__c/UPP_Notifications_Preferences__c.object-meta.xml
<CustomObject>
    <label>UPP Notifications Preferences</label>
    <nameField>
        <label>UPP Notifications Preferences Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>UPP Notifications Preferences</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/UPP_Notifications_Preferences__c/fields/Deliver_message_by_email__c.field-meta.xml
<CustomField>
    <fullName>Deliver_message_by_email__c</fullName>
    <defaultValue>false</defaultValue>
    <label>Deliver message by email</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/UPP_Notifications_Preferences__c/fields/Preferences__c.field-meta.xml
<CustomField>
    <fullName>Preferences__c</fullName>
    <label>Preferences</label>
    <type>MultiselectPicklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Missed Pickup Appointment</fullName>
            </value>
            <value>
                <fullName>New Price Announcement</fullName>
            </value>
            <value>
                <fullName>Past Due Shipment</fullName>
            </value>
            <value>
                <fullName>Scheduled Ship Date Change</fullName>
            </value>
            <value>
                <fullName>Sales Incentive Credit Message</fullName>
            </value>
            <value>
                <fullName>New Statement</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/UPP_Notifications_Preferences__c/fields/Records_per_page__c.field-meta.xml
<CustomField>
    <fullName>Records_per_page__c</fullName>
    <defaultValue>10</defaultValue>
    <label>Records per page</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/UPP_Notifications_Preferences__c/fields/User__c.field-meta.xml
<CustomField>
    <fullName>User__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>User</label>
    <referenceTo>User</referenceTo>
    <relationshipName>UPP_Notifications_Preferences</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/classes/UPPNotificationPreferenceSelector.cls
public without sharing class  UPPNotificationPreferenceSelector extends fflib_SObjectSelector {
    
    // Specify the SObject Type
    public  Schema.SObjectType getSObjectType() {
        return UPP_Notifications_Preferences__c.SObjectType;
    }
    
    // Specify the Fields to Query
    public  List<Schema.SObjectField> getSObjectFieldList() {
        return new List<Schema.SObjectField>{
            UPP_Notifications_Preferences__c.Id,
            UPP_Notifications_Preferences__c.Preferences__c,
            UPP_Notifications_Preferences__c.Deliver_Message_By_Email__c,
            UPP_Notifications_Preferences__c.Records_Per_Page__c,
            UPP_Notifications_Preferences__c.User__c
        };
    }
    
    // Method to Query User Preferences
    public List<UPP_Notifications_Preferences__c> selectPreferencesByUser(List<Id> userIds) {
        fflib_QueryFactory queryFactory = newQueryFactory();
        queryFactory.setCondition('User__c IN :userIds');
        queryFactory.setLimit(1);
        system.debug(queryFactory.toSOQL());
        return (List<UPP_Notifications_Preferences__c>) Database.query(queryFactory.toSOQL());
    }
}