force-app/main/default/objects/UPP_Document__c/UPP_Document__c.object-meta.xml
<CustomObject>
    <label>UPP Document</label>
    <nameField>
        <displayFormat>UPPS-{00000}</displayFormat>
        <label>UPP Document</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>UPP Documents</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/UPP_Document__c/fields/Amount_Due__c.field-meta.xml
<CustomField>
    <fullName>Amount_Due__c</fullName>
    <label>Amount Due</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/UPP_Document__c/fields/Entry_Type__c.field-meta.xml
<CustomField>
    <fullName>Entry_Type__c</fullName>
    <label>Entry Type</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/UPP_Document__c/fields/PO__c.field-meta.xml
<CustomField>
    <fullName>PO__c</fullName>
    <label>PO</label>
    <precision>6</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/UPP_Document__c/fields/Product2__c.field-meta.xml
<CustomField>
    <fullName>Product2__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Item Id</label>
    <referenceTo>Product2</referenceTo>
    <relationshipName>Items</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/UPP_Document__c/fields/Ship_to_City__c.field-meta.xml
<CustomField>
    <fullName>Ship_to_City__c</fullName>
    <label>Ship to City</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/UPP_Document__c/fields/UPP_Statement__c.field-meta.xml
<CustomField>
    <fullName>UPP_Statement__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>UPP Statement</label>
    <referenceTo>UPP_Statement__c</referenceTo>
    <relationshipLabel>UPP Documents</relationshipLabel>
    <relationshipName>UPP_Documents</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/UPP_Statement__c/UPP_Statement__c.object-meta.xml
<CustomObject>
    <label>UPP Statement</label>
    <nameField>
        <displayFormat>{0000}</displayFormat>
        <label>UPP Statement ID</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>UPP Statements</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/classes/UppDocumentSelector.cls
public inherited sharing class UppDocumentSelector extends fflib_SObjectSelector {
    
    // Return the SObjectType for UPP_Document__c
    public Schema.SObjectType getSObjectType() {
        return UPP_Document__c.SObjectType;
    }
    
    // Specify the fields to query for UPP_Document__c
    public List<Schema.SObjectField> getSObjectFieldList() {
        return new List<Schema.SObjectField>{
            UPP_Document__c.Product2__c,
            UPP_Document__c.Invoice_Date__c,
            UPP_Document__c.Due_Date__c,
            UPP_Document__c.Location__c,
            UPP_Document__c.Ship_to_City__c,
            UPP_Document__c.Entry_Type__c,
            UPP_Document__c.PO__c,
            UPP_Document__c.Amount_Due__c,
            UPP_Document__c.Currency__c
        };
    }
    
    
    public List<UPP_Document__c> selectDocumentsByStatementId(Id statementId) {
        
        
        // Instantiate the QueryFactory for Upp_Statement__c
        fflib_QueryFactory queryFactory = newQueryFactory();
        
        
        queryFactory.setCondition('Upp_Statement__c = :statementId');
        
        
        // Execute the query and return the results
        List<UPP_Document__c> documents = (List<UPP_Document__c>) Database.query(queryFactory.toSOQL());
        
        return documents;
    }
    
}