force-app/main/default/objects/UPP_Document__c/UPP_Document__c.object-meta.xml
<CustomObject>
    <label>UPP Document</label>
    <nameField>
        <displayFormat>UPPS-{00000}</displayFormat>
        <label>UPP Document</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>UPP Documents</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/UPP_Document__c/fields/UPP_Statement__c.field-meta.xml
<CustomField>
    <fullName>UPP_Statement__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>UPP Statement</label>
    <referenceTo>UPP_Statement__c</referenceTo>
    <relationshipLabel>UPP Documents</relationshipLabel>
    <relationshipName>UPP_Documents</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/UPP_Statement__c/UPP_Statement__c.object-meta.xml
<CustomObject>
    <label>UPP Statement</label>
    <nameField>
        <displayFormat>{0000}</displayFormat>
        <label>UPP Statement ID</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>UPP Statements</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/classes/StatementController.cls
public with sharing class StatementController {
    @AuraEnabled
    public static Map<String,Object> fetchStatementWithDocuments(Map<String,Object> statementFilter){
        
        Map<String,Object> statementResult = new Map<String,Object>();
        system.debug(Json.serializePretty(statementFilter));
        List<UPP_Statement__c> uppStatements ;
        UppStatementSelector statementSelector = new UppStatementSelector();
        if(statementFilter.containsKey('location') && statementFilter.containsKey('statementDate')){
            String location = String.valueOf(statementFilter.get('location'));
            Date statementDate = Date.valueOf((String)statementFilter.get('statementDate'));
            
            
            uppStatements = statementSelector.selectStatementsByLocationAndDate(location,statementDate);
            
            if(uppStatements.size()!=0){
                
                
                UppDocumentSelector documentSelector = new UppDocumentSelector();
                
                List<UPP_Document__c> relatedDocuments = documentSelector.selectDocumentsByStatementId(uppStatements[0].Id);
                
                statementResult.put('uppStatements',uppStatements);
                statementResult.put('relatedDocuments',relatedDocuments);
            }
        }
        else {
            system.debug('non filter');
            uppStatements = statementSelector.selectStatementsByLocationAndDate(null,null);
            statementResult.put('uppStatements',uppStatements);
            
        }
        
        return statementResult;
        
    }
    
}